"use client";
//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/global/navbar";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = usePathname();

  //const isHomePage = (router === "/" || router === "/our-works");
  const isHomePage = /^\/(our-works\/.*)?$/.test(router);

  return (
    <html lang="en">
      <body className={ " font-['Poppins']"}>
        <Navbar
          backgroundColor={isHomePage ? "transparent " : "#202EFF"}
          display={isHomePage ? "none" : "block"}
        />
        {children}
      </body>
    </html>
  );
}
